import { Place } from "@/types";

/**
 * 원곡동 다문화음식거리 장소 데이터.
 *
 * [수집 방법]
 * 카카오 로컬 API(키워드 장소 검색)로 거리 중심 좌표 반경 600m를 훑어
 * 실제 등록·영업 중인 가게만 채택했다. 이름을 추측해 넣지 않았다.
 * 중심 좌표는 관광공사 OpenAPI에 등록된 '안산다문화음식거리'
 * (37.32905, 126.790414)로, locationBasedList2 역조회 시 0m로 일치한다.
 *
 * [검증된 값]
 * - name / address(도로명) / tel / lat / lng / placeUrl: 지도 서비스에서 교차 확인한 값.
 * - 2026-08-29 네이버 지도와 전수 대조 후, 지도 서비스 간 통상적인 건물 중심점
 *   차이(약 1~4m)를 넘는 좌표는 네이버 등록 위치로 보정했다.
 * - walkMinutes: 안산역 4호선(37.326859, 126.789216)까지 직선거리에 보행 우회
 *   계수 1.3을 적용하고 분속 67m로 나눈 값.
 * - 세계문화체험관 운영 회차(1일 3회 10:30·13:30·15:00): 공식 안내 정보.
 * - 포토존 좌표: '안산 다문화특구'(다문화길 16) 공식 등록 좌표.
 *
 * [의도적으로 담지 않는 값]
 * - 영업시간·휴무·평점·리뷰: 카카오도 네이버도 공개 API로 제공하지 않는다.
 *   추정치를 사실처럼 보여주면 방문객이 헛걸음하므로, placeUrl(외부 지도 상세)로
 *   연결해 최신 정보를 직접 확인하게 한다.
 *
 * [남은 확인거리]
 * - tags(대표 메뉴)와 story는 해당 나라 음식 문화에 근거한 서술이다.
 *   가게별 실제 메뉴는 현장에서 확인해 보정할 것.
 */
export const SAMPLE_PLACES: Place[] = [
  // 2026-09-09: 네이버 장소 상세·메뉴·길찾기 도착 좌표 확인.
  {
    id: "kampung-indonesia",
    name: "캄풍인도네시아",
    category: "restaurant",
    district: "indonesia",
    lat: 37.3286206,
    lng: 126.7895629,
    address: "경기 안산시 단원구 다문화1길 1 2층",
    naverPlaceId: "2005595260",
    locationSource: "naver",
    nameAliases: ["Kampung Indonesia", "캄퐁인도네시아"],
    walkMinutes: 4,
    tel: "0507-1387-7325",
    tags: ["나시고랭", "렌당", "소갈비구이"],
    description: "다문화1길 2층에서 만나는 인도네시아 볶음밥·렌당·갈비구이",
  },
  {
    id: "warkop-indonesia",
    name: "워캅 인도네시아 레스토랑",
    category: "restaurant",
    district: "indonesia",
    lat: 37.3283045,
    lng: 126.7898508,
    address: "경기 안산시 단원구 중앙대로 455 2층",
    naverPlaceId: "2096306773",
    locationSource: "naver",
    nameAliases: ["Warkop", "워캅"],
    walkMinutes: 3,
    tel: "0507-1378-6736",
    tags: ["나시고랭", "바소", "오리튀김"],
    description: "안산역 건너편 2층, 볶음밥부터 미트볼 수프까지 고르는 인도네시아 식당",
  },
  {
    id: "rak-thai",
    name: "락타이",
    category: "restaurant",
    district: "thai",
    lat: 37.3297023,
    lng: 126.7921228,
    address: "경기 안산시 단원구 원곡로 25 2층",
    naverPlaceId: "2077293806",
    locationSource: "naver",
    nameAliases: ["Rak Thai", "락 타이"],
    walkMinutes: 8,
    tel: "0507-1346-7510",
    tags: ["똠얌꿍", "팟타이", "뿌팟퐁커리"],
    description: "원곡로 2층에서 똠얌꿍·볶음국수·게 커리를 만나는 태국 식당",
  },
  // ── 인도네시아 ────────────────────────────────────────────
  {
    id: "batavia",
    name: "바타비아",
    category: "restaurant",
    district: "indonesia",
    lat: 37.3284987,
    lng: 126.7897934,
    address: "경기 안산시 단원구 다문화길 4",
    naverPlaceId: "38009430",
    locationSource: "naver",
    walkMinutes: 4,
    placeUrl: "http://place.map.kakao.com/16020778",
    tags: ["나시고렝", "미고렝", "할랄"],
    description: "다문화길 입구 쪽 인도네시아 식당",
    story:
      "바타비아는 인도네시아 수도 자카르타의 식민지 시절 옛 이름입니다. 볶음밥 나시고렝과 볶음면 미고렝은 인도네시아 어디서나 만나는 국민 음식으로, 무슬림 인구가 많아 돼지고기를 쓰지 않는 할랄 조리가 기본입니다.",
    stampSlot: "indonesia",
    quiz: {
      question: "'바타비아'는 인도네시아 어느 도시의 옛 이름일까요?",
      options: ["자카르타", "발리", "반둥"],
      answerIndex: 0,
      hint: "이 가게의 문화 스토리에 답이 있어요.",
    },
  },
  {
    id: "aneka-rasa",
    name: "아네카라사",
    category: "restaurant",
    district: "indonesia",
    lat: 37.3292769,
    lng: 126.7900057,
    address: "경기 안산시 단원구 다문화길 11 2층",
    naverPlaceId: "2016185515",
    locationSource: "naver",
    walkMinutes: 5,
    tel: "031-492-8616",
    placeUrl: "http://place.map.kakao.com/328148291",
    tags: ["른당", "사테", "할랄"],
    description: "'여러 가지 맛'이라는 뜻의 인도네시아 가정식",
    story:
      "'아네카 라사(Aneka Rasa)'는 인도네시아어로 '여러 가지 맛'을 뜻합니다. 코코넛 밀크와 향신료로 소고기를 오래 조린 른당은 인도네시아를 대표하는 요리로 꼽힙니다.",
    stampSlot: "indonesia",
    quiz: {
      question: "'아네카 라사'는 인도네시아어로 어떤 뜻일까요?",
      options: ["여러 가지 맛", "고향의 맛", "바다의 맛"],
      answerIndex: 0,
      hint: "이 가게의 문화 스토리에 답이 있어요.",
    },
  },
  {
    id: "nusantara",
    name: "누산따라",
    category: "restaurant",
    district: "indonesia",
    lat: 37.3302188,
    lng: 126.7910566,
    address: "경기 안산시 단원구 다문화2길 28 지하 1층",
    naverPlaceId: "1631000930",
    locationSource: "naver",
    walkMinutes: 8,
    placeUrl: "http://place.map.kakao.com/2123173888",
    tags: ["나시고렝", "인도네시아커피", "할랄"],
    description: "인도네시아 열도 전체를 뜻하는 이름의 아시아 음식점",
    story:
      "'누산따라(Nusantara)'는 인도네시아 열도 전체를 가리키는 말로, 1만 7천여 개의 섬을 아우르는 이름입니다. 섬마다 향신료와 조리법이 달라 인도네시아 음식은 지역색이 매우 강합니다.",
    stampSlot: "indonesia",
    quiz: {
      question: "'누산따라'는 무엇을 가리키는 말일까요?",
      options: ["인도네시아 열도 전체", "자바섬의 옛 왕국", "향신료 시장"],
      answerIndex: 0,
      hint: "이 가게의 문화 스토리에 답이 있어요.",
    },
  },

  // ── 중국동포 ──────────────────────────────────────────────
  {
    id: "taesan-skewer",
    name: "태산양꼬치",
    category: "restaurant",
    district: "chinese",
    lat: 37.3311746,
    lng: 126.7909879,
    address: "경기 안산시 단원구 원본로 10 1층",
    nameAliases: ["태산양꼬치 원곡점"],
    naverPlaceId: "1934697881",
    locationSource: "naver",
    walkMinutes: 10,
    placeUrl: "http://place.map.kakao.com/1542205016",
    tags: ["양꼬치", "꼬치구이"],
    description: "숯불 양꼬치 전문점",
    story:
      "숯불에 꼬치를 돌려 굽는 양꼬치는 중국 동북지방에서 밤 문화와 함께 자란 음식입니다. 원곡동 저녁 골목의 냄새를 만드는 주인공으로, 원본로 일대에 양꼬치집이 특히 밀집해 있습니다.",
    stampSlot: "chinese",
    quiz: {
      question: "양꼬치를 밤 문화와 함께 즐기는 문화가 자란 지역은?",
      options: ["중국 동북지방", "중국 남부 해안", "티베트 고원"],
      answerIndex: 0,
      hint: "이 가게의 문화 스토리에 답이 있어요.",
    },
  },
  {
    id: "yanji-tofu",
    name: "연길초두부",
    category: "restaurant",
    district: "chinese",
    lat: 37.3310872,
    lng: 126.7910741,
    address: "경기 안산시 단원구 원본로 10-1 1층",
    naverPlaceId: "1347596666",
    locationSource: "naver",
    walkMinutes: 10,
    tel: "031-495-0043",
    placeUrl: "http://place.map.kakao.com/14720595",
    tags: ["초두부", "연변음식"],
    description: "연변식 초두부를 내는 중국동포 식당",
    story:
      "연길(옌지)은 중국 지린성 연변조선족자치주의 중심 도시입니다. 초두부는 응고되기 전의 순두부에 양념장을 얹어 먹는 연변 가정식으로, 중국동포 공동체의 아침 식탁에 자주 오릅니다.",
    stampSlot: "chinese",
    quiz: {
      question: "'연길(옌지)'은 어느 자치주의 중심 도시일까요?",
      options: ["연변조선족자치주", "내몽골자치구", "신장위구르자치구"],
      answerIndex: 0,
      hint: "이 가게의 문화 스토리에 답이 있어요.",
    },
  },
  {
    id: "chunhyangsan",
    name: "춘향산",
    category: "restaurant",
    district: "chinese",
    lat: 37.3301673,
    lng: 126.7931582,
    address: "경기 안산시 단원구 원본로 32",
    naverPlaceId: "31664333",
    locationSource: "naver",
    walkMinutes: 10,
    placeUrl: "http://place.map.kakao.com/15814267",
    tags: ["마라탕", "중국요리", "매운맛"],
    description: "재료를 골라 담는 마라탕집",
    story:
      "마라(麻辣)는 혀가 저릿한 '마'와 매운 '라'가 합쳐진 맛으로, 쓰촨 지방의 화자오(산초)에서 옵니다. 원하는 재료를 그릇에 담아 무게로 계산하는 방식은 중국 길거리 음식 문화가 그대로 넘어온 것입니다.",
    stampSlot: "chinese",
    quiz: {
      question: "마라탕의 '마(麻)'는 어떤 느낌을 뜻할까요?",
      options: ["혀가 저릿한 느낌", "짠맛", "새콤한 맛"],
      answerIndex: 0,
      hint: "이 가게의 문화 스토리에 답이 있어요.",
    },
  },

  // ── 베트남 ────────────────────────────────────────────────
  {
    id: "vietnam-hometown",
    name: "베트남고향식당",
    category: "restaurant",
    district: "vietnam",
    lat: 37.3287985,
    lng: 126.7887959,
    address: "경기 안산시 단원구 중앙대로 443",
    naverPlaceId: "13332007",
    locationSource: "naver",
    walkMinutes: 4,
    tel: "031-492-0865",
    placeUrl: "http://place.map.kakao.com/8333899",
    tags: ["쌀국수", "분짜"],
    description: "안산역에서 가장 가까운 베트남 식당",
    story:
      "'고향'이라는 이름처럼 베트남 이주민들이 고향의 맛을 찾아 모이는 곳입니다. 베트남에서 쌀국수(포)는 새벽 육수 냄새로 하루를 여는 아침 음식입니다.",
    stampSlot: "vietnam",
    quiz: {
      question: "베트남에서 쌀국수(포)는 주로 언제 먹는 음식일까요?",
      options: ["아침", "야식", "명절에만"],
      answerIndex: 0,
      hint: "이 가게의 문화 스토리에 답이 있어요.",
    },
  },
  {
    id: "dieu-hien-quan",
    name: "디유히엔콴",
    category: "restaurant",
    district: "vietnam",
    lat: 37.3289837,
    lng: 126.7893139,
    address: "경기 안산시 단원구 다문화1길 6",
    naverPlaceId: "19489630",
    locationSource: "naver",
    walkMinutes: 5,
    tel: "031-493-3756",
    placeUrl: "http://place.map.kakao.com/15626144",
    tags: ["쌀국수", "베트남음식"],
    description: "다문화1길 골목의 베트남 식당",
    story:
      "베트남어에서 '콴(Quán)'은 작은 밥집·가게를 뜻합니다. 상호에 콴이 붙은 집은 현지에서도 동네 사람들이 편하게 드나드는 식당이라는 뜻으로 읽힙니다.",
    stampSlot: "vietnam",
    quiz: {
      question: "베트남어 '콴(Quán)'은 어떤 뜻일까요?",
      options: ["작은 밥집·가게", "국수", "시장"],
      answerIndex: 0,
      hint: "이 가게의 문화 스토리에 답이 있어요.",
    },
  },

  // ── 태국 ──────────────────────────────────────────────────
  {
    id: "suwal-thai",
    name: "수왈태국레스토랑",
    category: "restaurant",
    district: "thai",
    lat: 37.329691,
    lng: 126.790667,
    address: "경기 안산시 단원구 다문화길 18 4층",
    locationSource: "kakao",
    walkMinutes: 7,
    tel: "031-494-0338",
    placeUrl: "http://place.map.kakao.com/2015373823",
    tags: ["똠얌꿍", "팟타이", "매운맛"],
    description: "다문화길 태국 음식 전문점",
    story:
      "세계 3대 수프로 꼽히는 똠얌꿍은 레몬그라스·갈랑갈·라임잎을 넣어 신맛과 매운맛을 동시에 냅니다. 신맛·단맛·매운맛·짠맛을 한 그릇에 담는 균형이 태국 음식의 핵심입니다.",
    stampSlot: "thai",
    quiz: {
      question: "세계 3대 수프로 꼽히는 태국 음식은 무엇일까요?",
      options: ["똠얌꿍", "팟타이", "쏨땀"],
      answerIndex: 0,
      hint: "이 가게의 문화 스토리에 답이 있어요.",
    },
  },
  {
    id: "pad-thai",
    name: "팟타이",
    category: "restaurant",
    district: "thai",
    lat: 37.3291491,
    lng: 126.7885713,
    address: "경기 안산시 단원구 부부로 4 1층",
    naverPlaceId: "32875053",
    locationSource: "naver",
    walkMinutes: 5,
    tel: "070-4176-0562",
    placeUrl: "http://place.map.kakao.com/19272308",
    tags: ["팟타이", "태국음식"],
    description: "태국 대표 볶음면을 상호로 쓴 식당",
    story:
      "팟타이는 쌀국수를 타마린드 소스에 볶아 땅콩과 라임을 곁들이는 태국의 국민 볶음면입니다. 20세기 중반 정부가 쌀 소비를 줄이려 국수 요리를 장려하면서 전국으로 퍼진 음식입니다.",
    stampSlot: "thai",
    quiz: {
      question: "팟타이의 새콤한 맛은 주로 무엇에서 올까요?",
      options: ["타마린드", "식초", "매실"],
      answerIndex: 0,
      hint: "이 가게의 문화 스토리에 답이 있어요.",
    },
  },

  // ── 인도·네팔 ─────────────────────────────────────────────
  {
    id: "kantipur",
    name: "칸티푸르레스토랑",
    category: "restaurant",
    district: "southasia",
    lat: 37.3302188,
    lng: 126.7910566,
    address: "경기 안산시 단원구 다문화2길 28 2층",
    nameAliases: ["칸티푸르 안산점"],
    naverPlaceId: "19882027",
    locationSource: "naver",
    walkMinutes: 8,
    tel: "031-493-9563",
    placeUrl: "http://place.map.kakao.com/14100981",
    tags: ["달밧", "모모", "탄두리"],
    description: "네팔 카트만두의 옛 이름을 딴 식당",
    story:
      "칸티푸르는 네팔 카트만두의 옛 이름입니다. 네팔 가정식 정식인 달밧은 렌틸콩 수프(달)와 밥(밧)을 기본으로 반찬을 곁들이는 한 상 차림이고, 모모는 히말라야를 넘어온 만두입니다.",
    stampSlot: "southasia",
    quiz: {
      question: "'칸티푸르'는 네팔 어느 도시의 옛 이름일까요?",
      options: ["포카라", "카트만두", "룸비니"],
      answerIndex: 1,
      hint: "이 가게의 문화 스토리에 답이 있어요.",
    },
  },
  {
    id: "new-taj-mahal",
    name: "뉴타지마할",
    category: "restaurant",
    district: "southasia",
    lat: 37.3305904,
    lng: 126.791731,
    address: "경기 안산시 단원구 다문화1길 49",
    naverPlaceId: "35366122",
    locationSource: "naver",
    walkMinutes: 9,
    tel: "031-492-7861",
    placeUrl: "http://place.map.kakao.com/15619465",
    tags: ["커리", "탄두리치킨", "난", "매운맛"],
    description: "화덕에서 굽는 인도 음식점",
    story:
      "탄두르는 진흙으로 만든 항아리 화덕으로, 안쪽 벽에 반죽을 붙여 난을 굽고 꼬치를 세워 고기를 굽습니다. 400도가 넘는 열로 짧게 익혀 겉은 그을리고 속은 촉촉한 것이 특징입니다.",
    stampSlot: "southasia",
    quiz: {
      question: "인도의 진흙 화덕을 무엇이라 부를까요?",
      options: ["탄두르", "차파티", "마살라"],
      answerIndex: 0,
      hint: "이 가게의 문화 스토리에 답이 있어요.",
    },
  },

  // ── 중앙아시아·튀르키예 ───────────────────────────────────
  {
    id: "samarkand",
    name: "사마르칸트",
    category: "restaurant",
    district: "centralasia",
    lat: 37.3290354,
    lng: 126.7896312,
    address: "경기 안산시 단원구 다문화2길 3",
    nameAliases: ["후르셰다사마르칸트"],
    naverPlaceId: "19877526",
    locationSource: "naver",
    walkMinutes: 5,
    tel: "031-492-6984",
    placeUrl: "http://place.map.kakao.com/11833940",
    tags: ["샤슬릭", "플롭", "리뽀시카"],
    description: "우즈베키스탄 화덕 요리 식당",
    story:
      "사마르칸트는 실크로드의 심장이라 불리는 우즈베키스탄의 고도(古都)입니다. 쇠꼬챙이에 꽂아 숯불에 굽는 샤슬릭, 잔치마다 큰 솥으로 짓는 볶음밥 플롭, 화덕에 붙여 굽는 둥근 빵 리뽀시카가 중앙아시아 잔칫상의 기본입니다.",
    stampSlot: "centralasia",
    quiz: {
      question: "'사마르칸트'는 어떤 옛 교역로의 중심 도시였을까요?",
      options: ["실크로드", "차마고도", "향신료 항로"],
      answerIndex: 0,
      hint: "이 가게의 문화 스토리에 답이 있어요.",
    },
  },
  {
    id: "imperia-food",
    name: "임페리아푸드",
    category: "grocery",
    district: "centralasia",
    lat: 37.3314405,
    lng: 126.7964542,
    address: "경기 안산시 단원구 화랑로 33 101호·102호",
    naverPlaceId: "1292227894",
    locationSource: "naver",
    walkMinutes: 16,
    googlePlaceId: "ChIJh_gpIcxvezURjFvgFJF4ow4",
    placeUrl:
      "https://www.google.com/maps/search/?api=1&query=%EC%9E%84%ED%8E%98%EB%A6%AC%EC%95%84%ED%91%B8%EB%93%9C&query_place_id=ChIJh_gpIcxvezURjFvgFJF4ow4",
    tags: ["러시아빵", "수입식품", "메도빅"],
    description: "러시아·중앙아시아 식재료를 파는 식품점",
    story:
      "고기나 채소를 넣은 러시아식 파이 피로시키와 유럽 식재료를 함께 파는 곳으로, 러시아어권 주민들의 장보기 코스입니다. 꿀을 켜켜이 쌓아 만드는 러시아 케이크 메도빅도 이 계열 가게에서 만날 수 있습니다.",
    stampSlot: "centralasia",
    quiz: {
      question: "꿀을 켜켜이 쌓아 만드는 러시아 케이크의 이름은?",
      options: ["메도빅", "블리니", "피로시키"],
      answerIndex: 0,
      hint: "이 가게의 문화 스토리에 답이 있어요.",
    },
  },
  {
    id: "troy-kebab",
    name: "트로이케밥",
    category: "restaurant",
    district: "centralasia",
    lat: 37.3294055,
    lng: 126.7900907,
    address: "경기 안산시 단원구 다문화길 13 101호",
    naverPlaceId: "1419070836",
    locationSource: "naver",
    walkMinutes: 6,
    placeUrl: "http://place.map.kakao.com/1754357281",
    tags: ["되네르케밥", "튀르키예음식"],
    description: "다문화길 한복판의 튀르키예 케밥집",
    story:
      "되네르(döner)는 튀르키예어로 '돌아가는'이라는 뜻입니다. 세로 꼬치에 고기를 층층이 쌓아 회전시키며 겉면부터 얇게 깎아내는 방식으로, 튀르키예에서 시작해 유럽 전역의 길거리 음식이 되었습니다.",
    stampSlot: "centralasia",
    quiz: {
      question: "'되네르(döner)'는 튀르키예어로 어떤 뜻일까요?",
      options: ["돌아가는", "구운", "매운"],
      answerIndex: 0,
      hint: "이 가게의 문화 스토리에 답이 있어요.",
    },
  },

  // ── 이웃의 생활 ───────────────────────────────────────────
  // 음식점만 늘어놓으면 '먹고 또 먹는' 거리가 된다. 주민들이 실제로 장을 보는
  // 곳을 함께 두어야 이 골목에서 어떤 사람들이 어떻게 살아가는지가 보인다.
  // 한국 빵집·프랜차이즈는 넣지 않았다 — 카카오 분류로 국적이 확인되는 곳만 담는다.
  {
    id: "almodina-halal",
    name: "알머디나할랄마트",
    category: "grocery",
    district: "southasia",
    lat: 37.331092,
    lng: 126.790184,
    address: "경기 안산시 단원구 다문화1길 33-1",
    locationSource: "kakao",
    walkMinutes: 9,
    tel: "070-8234-1658",
    nameAliases: ["알모디나할랄마트"],
    placeUrl: "http://place.map.kakao.com/1827593180",
    tags: ["할랄", "향신료", "수입식품"],
    description: "무슬림 주민들이 장을 보는 할랄 식품점",
    story:
      "할랄은 이슬람 율법에서 '허용된 것'을 뜻합니다. 정해진 방식으로 도축한 고기와 돼지고기·주류가 섞이지 않은 재료를 뜻해, 무슬림 주민에게는 식당보다 이런 마트가 더 중요한 생활 기반입니다. 원곡동에 할랄마트가 여러 곳 있다는 것 자체가 이 동네에 무슬림 공동체가 자리 잡았다는 증거입니다.",
  },
  {
    id: "lepeshka-market",
    name: "레표시카",
    category: "grocery",
    district: "centralasia",
    lat: 37.3325702,
    lng: 126.796158,
    address: "경기 안산시 단원구 화랑로 22",
    naverPlaceId: "1027895937",
    locationSource: "naver",
    walkMinutes: 18,
    googlePlaceId: "ChIJSSD6kc5vezURPQgLmPp_ZlM",
    placeUrl:
      "https://www.google.com/maps/search/?api=1&query=%EB%A0%88%ED%91%9C%EC%8B%9C%EC%B9%B4&query_place_id=ChIJSSD6kc5vezURPQgLmPp_ZlM",
    tags: ["우즈베키스탄빵", "러시아식품", "수입식품"],
    description: "우즈베키스탄 화덕빵과 러시아·중앙아시아 식료품을 파는 가게",
    story:
      "레표시카(лепёшка)는 둥글고 납작한 중앙아시아식 빵을 뜻합니다. 탄디르 화덕 벽에 반죽을 붙여 구우며, 현지에서는 매일 식탁에 오르는 주식에 가깝습니다. 이곳에서는 빵과 함께 러시아·중앙아시아권 식료품도 살펴볼 수 있습니다.",
  },
  {
    id: "world-food-market",
    name: "월드푸드",
    category: "grocery",
    district: "indonesia",
    lat: 37.3295431,
    lng: 126.7902361,
    address: "경기 안산시 단원구 다문화길 13-1",
    naverPlaceId: "1925916355",
    locationSource: "naver",
    walkMinutes: 6,
    googlePlaceId: "ChIJf0id1tJvezURXAtjZWEusjY",
    placeUrl:
      "https://www.google.com/maps/search/?api=1&query=%EC%9B%94%EB%93%9C%ED%91%B8%EB%93%9C&query_place_id=ChIJf0id1tJvezURXAtjZWEusjY",
    tags: ["동남아식품", "열대과일", "수입식품"],
    description: "동남아 식재료와 열대과일을 갖춘 아시아 식료품점",
    story:
      "다문화 식료품점은 낯선 식재료를 구경하는 관광 공간인 동시에 이주민이 고향의 맛을 이어 가는 생활 기반입니다. 이곳에서는 동남아 조미료와 면류, 열대과일처럼 일반 마트에서 찾기 어려운 식재료를 만날 수 있습니다.",
  },
  {
    id: "k2-nepal",
    name: "K2네팔존",
    category: "grocery",
    district: "southasia",
    lat: 37.330539,
    lng: 126.789766,
    address: "경기 안산시 단원구 다문화1길 27",
    locationSource: "kakao",
    walkMinutes: 8,
    placeUrl: "http://place.map.kakao.com/1949748844",
    tags: ["네팔식품", "향신료", "렌틸콩"],
    description: "네팔 주민들의 식료품점",
    story:
      "가게 이름의 K2는 히말라야 두 번째로 높은 봉우리에서 왔습니다. 달밧에 쓰는 렌틸콩과 향신료처럼 한국 마트에서 구하기 어려운 재료를 파는 곳으로, 네팔 주민들이 고향 음식을 계속 해 먹을 수 있게 해주는 자리입니다.",
  },
  {
    id: "sin-china-food",
    name: "신중국식품",
    category: "grocery",
    district: "chinese",
    lat: 37.330336,
    lng: 126.7908405,
    address: "경기 안산시 단원구 다문화2길 26",
    naverPlaceId: "1992178661",
    locationSource: "naver",
    walkMinutes: 8,
    tel: "031-492-8062",
    placeUrl: "http://place.map.kakao.com/16769778",
    tags: ["중국식품", "향신료", "냉동만두"],
    description: "중국·조선족 주민들이 찾는 식품점",
    story:
      "화자오(산초)와 팔각처럼 중국 요리의 바탕이 되는 향신료, 고향에서 먹던 냉동식품과 절임류를 파는 곳입니다. 원곡동에 중국 식품점이 여러 곳 있는 이유는 단순합니다 — 주민의 71%가 중국계이기 때문입니다.",
  },

  // ── 더 둘러보기 ─────────────────────────────────────────
  // 카카오 로컬 API로 함께 확인된 가게들. 스탬프 대상은 위의 대표 가게들이라
  // stampSlot을 두지 않고, 지도·목록에서 골목의 실제 밀도를 보여주는 역할을 한다.
  {
    id: "jakarta-resto",
    name: "자카르타",
    category: "restaurant",
    district: "indonesia",
    lat: 37.32836,
    lng: 126.7896922,
    address: "경기 안산시 단원구 중앙대로 453 2층",
    naverPlaceId: "1195762000",
    locationSource: "naver",
    walkMinutes: 3,
    placeUrl: "http://place.map.kakao.com/1023213709",
    tags: ["나시고렝", "할랄"],
    description: "인도네시아 수도 이름을 단 아시아 음식점",
  },
  {
    id: "gatotkaca",
    name: "가톳카차",
    category: "restaurant",
    district: "indonesia",
    lat: 37.3304913,
    lng: 126.7909129,
    address: "경기 안산시 단원구 다문화2길 25 2층",
    naverPlaceId: "1320684060",
    locationSource: "naver",
    walkMinutes: 8,
    placeUrl: "http://place.map.kakao.com/1519656441",
    tags: ["나시고렝", "할랄"],
    description: "자바 전통 인형극 영웅의 이름을 딴 식당",
  },
  {
    id: "warung-kita",
    name: "와룽키타",
    category: "restaurant",
    district: "indonesia",
    lat: 37.3316993,
    lng: 126.7904975,
    address: "경기 안산시 단원구 원본로 3 1층",
    naverPlaceId: "1642151859",
    locationSource: "naver",
    walkMinutes: 11,
    placeUrl: "http://place.map.kakao.com/11614889",
    tags: ["나시고렝", "인도네시아가정식"],
    description: "'우리 가게'라는 뜻의 인도네시아 식당",
  },
  {
    id: "royal-resto",
    name: "로얄레스토랑",
    category: "restaurant",
    district: "indonesia",
    lat: 37.3295102,
    lng: 126.791996,
    address: "경기 안산시 단원구 원곡로 23 2-3층",
    naverPlaceId: "1515511883",
    locationSource: "naver",
    walkMinutes: 7,
    placeUrl: "http://place.map.kakao.com/948611148",
    tags: ["동남아음식"],
    description: "원곡로 아시아 음식점",
  },
  {
    id: "asiana-resto",
    name: "아시아나레스토랑",
    category: "restaurant",
    district: "southasia",
    lat: 37.3287908,
    lng: 126.7900394,
    address: "경기 안산시 단원구 다문화2길 51 2층",
    naverPlaceId: "31197731",
    locationSource: "naver",
    walkMinutes: 4,
    placeUrl: "http://place.map.kakao.com/15854118",
    tags: ["커리", "난", "매운맛"],
    description: "다문화2길 인도 음식점",
  },
  {
    id: "agan-resto",
    name: "아건레스토랑&바르",
    category: "restaurant",
    district: "southasia",
    lat: 37.328694,
    lng: 126.789872,
    address: "경기 안산시 단원구 다문화길 6 2층",
    locationSource: "kakao",
    walkMinutes: 4,
    tel: "070-4045-7307",
    placeUrl: "http://place.map.kakao.com/648436253",
    tags: ["커리", "인도음식", "매운맛"],
    description: "다문화길 초입의 인도 음식점 겸 바",
  },
  {
    id: "solti",
    name: "솔티인도네팔음식점",
    category: "restaurant",
    district: "southasia",
    lat: 37.3283616,
    lng: 126.7897036,
    address: "경기 안산시 단원구 중앙대로 453 3층",
    nameAliases: ["솔티 인도네팔레스토랑"],
    naverPlaceId: "1341937209",
    locationSource: "naver",
    walkMinutes: 3,
    tel: "031-492-7723",
    placeUrl: "http://place.map.kakao.com/1033281933",
    tags: ["커리", "달밧", "매운맛"],
    description: "인도와 네팔 음식을 함께 내는 식당",
  },
  {
    id: "nirosa",
    name: "니로사레스토랑",
    category: "restaurant",
    district: "southasia",
    lat: 37.3292534,
    lng: 126.7917967,
    address: "경기 안산시 단원구 원곡로 19 3층",
    nameAliases: ["니로사레스토랑 안산점"],
    naverPlaceId: "2066616148",
    locationSource: "naver",
    walkMinutes: 7,
    placeUrl: "http://place.map.kakao.com/1894656304",
    tags: ["커리", "탄두리", "매운맛"],
    description: "원곡로 인도 음식점",
  },
  {
    id: "indo-nepal",
    name: "인도네팔음식점",
    category: "restaurant",
    district: "southasia",
    lat: 37.3310924,
    lng: 126.7899177,
    address: "경기 안산시 단원구 부부로 28-1 2층",
    nameAliases: ["인도네팔음식점 네팔리 번사거르"],
    naverPlaceId: "1725949596",
    locationSource: "naver",
    walkMinutes: 9,
    placeUrl: "http://place.map.kakao.com/1850542077",
    tags: ["커리", "모모", "매운맛"],
    description: "부부로 인도·네팔 음식점",
  },
  {
    id: "injing-myanmar",
    name: "인징미얀마레스토랑",
    category: "restaurant",
    district: "southasia",
    lat: 37.329692,
    lng: 126.790667,
    address: "경기 안산시 단원구 다문화길 18 4층",
    locationSource: "kakao",
    walkMinutes: 7,
    placeUrl: "http://place.map.kakao.com/1788123999",
    tags: ["미얀마음식", "샨국수"],
    description: "다문화길의 미얀마 음식점",
  },
  {
    id: "thai-noodle",
    name: "태국쌀국수",
    category: "restaurant",
    district: "thai",
    lat: 37.3309167,
    lng: 126.7897723,
    address: "경기 안산시 단원구 부부로 26",
    naverPlaceId: "1499170135",
    locationSource: "naver",
    walkMinutes: 9,
    placeUrl: "http://place.map.kakao.com/15464312",
    tags: ["쌀국수", "태국음식"],
    description: "부부로 태국 쌀국수집",
  },
  {
    id: "duk-kun",
    name: "덕쿤",
    category: "restaurant",
    district: "thai",
    lat: 37.3262236,
    lng: 126.7938088,
    address: "경기 안산시 단원구 원일1길 11 1층",
    naverPlaceId: "2037941809",
    locationSource: "naver",
    walkMinutes: 8,
    placeUrl: "http://place.map.kakao.com/1752968174",
    tags: ["태국음식"],
    description: "원일1길 태국 음식점",
  },
  {
    id: "woaini",
    name: "워아이니양꼬치훠궈뷔페",
    category: "restaurant",
    district: "chinese",
    lat: 37.328767,
    lng: 126.791909,
    address: "경기 안산시 단원구 원곡로 16-1 1층",
    locationSource: "kakao",
    walkMinutes: 6,
    placeUrl: "http://place.map.kakao.com/1513176220",
    tags: ["양꼬치", "훠궈뷔페"],
    description: "양꼬치와 훠궈를 뷔페로 내는 집",
  },
  {
    id: "cheonmaeja",
    name: "천매자",
    category: "restaurant",
    district: "chinese",
    lat: 37.3288344,
    lng: 126.7915573,
    address: "경기 안산시 단원구 원곡로 15 용진빌딩",
    nameAliases: ["훠궈 천매자"],
    naverPlaceId: "894918536",
    locationSource: "naver",
    walkMinutes: 6,
    tel: "031-492-7771",
    placeUrl: "http://place.map.kakao.com/1750695499",
    tags: ["훠궈", "샤브샤브"],
    description: "원곡로 훠궈·샤브샤브 전문점",
  },
  {
    id: "lingongzi",
    name: "린궁즈",
    category: "restaurant",
    district: "chinese",
    lat: 37.3296468,
    lng: 126.790658,
    address: "경기 안산시 단원구 다문화길 18",
    nameAliases: ["린궁즈멘관"],
    naverPlaceId: "2082886359",
    locationSource: "naver",
    walkMinutes: 7,
    placeUrl: "http://place.map.kakao.com/1160254882",
    tags: ["중국요리"],
    description: "다문화길 중국요리집",
  },
  {
    id: "ottugi-noodle",
    name: "오뚜기수타면",
    category: "restaurant",
    district: "chinese",
    lat: 37.3295314,
    lng: 126.7920391,
    address: "경기 안산시 단원구 원곡로 23",
    naverPlaceId: "1292837179",
    locationSource: "naver",
    walkMinutes: 7,
    placeUrl: "http://place.map.kakao.com/1426699046",
    tags: ["수타면", "도삭면"],
    description: "손으로 뽑는 수타면집",
  },
  {
    id: "beijing-duck",
    name: "북경오리구이",
    category: "restaurant",
    district: "chinese",
    lat: 37.3303421,
    lng: 126.7913055,
    address: "경기 안산시 단원구 다문화2길 29 1층",
    nameAliases: ["복린다 북경오리구이 본점"],
    naverPlaceId: "31601277",
    locationSource: "naver",
    walkMinutes: 8,
    tel: "031-495-6062",
    placeUrl: "http://place.map.kakao.com/20487282",
    tags: ["베이징덕", "오리요리"],
    description: "다문화2길 북경오리 전문점",
  },
  {
    id: "gangttuk",
    name: "안산원조강뚝꼬치구이",
    category: "restaurant",
    district: "chinese",
    lat: 37.3292346,
    lng: 126.7923029,
    address: "경기 안산시 단원구 원곡로 22-1 1층",
    nameAliases: ["안산원조강뚝꼬치구이전문점"],
    naverPlaceId: "2022371891",
    locationSource: "naver",
    walkMinutes: 7,
    tel: "0503-7153-8456",
    placeUrl: "http://place.map.kakao.com/864708783",
    tags: ["양꼬치", "꼬치구이"],
    description: "원곡로 꼬치구이 전문점",
  },
  {
    id: "sinbukgyeong",
    name: "신북경마라탕",
    category: "restaurant",
    district: "chinese",
    lat: 37.329794,
    lng: 126.792178,
    address: "경기 안산시 단원구 원곡로 27",
    locationSource: "kakao",
    walkMinutes: 8,
    tel: "031-492-2018",
    placeUrl: "http://place.map.kakao.com/19163255",
    tags: ["마라탕", "마라샹궈", "매운맛"],
    description: "원곡로 마라탕집",
  },
  {
    id: "mama-gyoja",
    name: "마마교자관",
    category: "restaurant",
    district: "chinese",
    lat: 37.3300551,
    lng: 126.792868,
    address: "경기 안산시 단원구 원곡로 34 1층",
    naverPlaceId: "1188709063",
    locationSource: "naver",
    walkMinutes: 9,
    tel: "031-491-2888",
    placeUrl: "http://place.map.kakao.com/15480316",
    tags: ["교자", "만두"],
    description: "손만두를 빚는 교자 전문점",
  },
  {
    id: "bokwang-mandu",
    name: "복왕만두",
    category: "restaurant",
    district: "chinese",
    lat: 37.331498,
    lng: 126.790944,
    address: "경기 안산시 단원구 원본로 7",
    locationSource: "kakao",
    walkMinutes: 10,
    placeUrl: "http://place.map.kakao.com/262404805",
    tags: ["만두", "분식"],
    description: "원본로 만두집",
  },
  {
    id: "yanji-skewer2",
    name: "연길양꼬치",
    category: "restaurant",
    district: "chinese",
    lat: 37.3312389,
    lng: 126.792366,
    address: "경기 안산시 단원구 부부로1길 19",
    naverPlaceId: "1122183917",
    locationSource: "naver",
    walkMinutes: 11,
    tel: "031-495-3345",
    placeUrl: "http://place.map.kakao.com/1134917813",
    tags: ["양꼬치"],
    description: "부부로1길 양꼬치집",
  },
  {
    id: "janggang",
    name: "장강반점",
    category: "restaurant",
    district: "chinese",
    lat: 37.3312,
    lng: 126.7925152,
    address: "경기 안산시 단원구 부부로1길 21",
    naverPlaceId: "1433240813",
    locationSource: "naver",
    walkMinutes: 11,
    tel: "031-493-1398",
    placeUrl: "http://place.map.kakao.com/15809072",
    tags: ["중국요리", "짜장면"],
    description: "부부로1길 중국요리집",
  },
  {
    id: "jindallae-naengmyeon",
    name: "연길진달래냉면",
    category: "restaurant",
    district: "chinese",
    lat: 37.3316141,
    lng: 126.7926214,
    address: "경기 안산시 단원구 원본로1길 10-5",
    naverPlaceId: "1265696444",
    locationSource: "naver",
    walkMinutes: 12,
    tel: "031-492-3881",
    placeUrl: "http://place.map.kakao.com/8479088",
    tags: ["옌지냉면", "냉면"],
    description: "연변식 냉면 전문점",
  },
  {
    id: "ttungbo",
    name: "뚱보양꼬치",
    category: "restaurant",
    district: "chinese",
    lat: 37.3312012,
    lng: 126.7908371,
    address: "경기 안산시 단원구 원본로 8-1",
    naverPlaceId: "176164190",
    locationSource: "naver",
    walkMinutes: 10,
    placeUrl: "http://place.map.kakao.com/1636007853",
    tags: ["양꼬치"],
    description: "원본로 양꼬치집",
  },
  {
    id: "sarai-kebab",
    name: "사라이도네르케밥",
    category: "restaurant",
    district: "centralasia",
    lat: 37.3287996,
    lng: 126.7919063,
    address: "경기 안산시 단원구 원곡로 16-1 1층",
    naverPlaceId: "1897108364",
    locationSource: "naver",
    walkMinutes: 6,
    tel: "031-495-0788",
    placeUrl: "http://place.map.kakao.com/1276420660",
    tags: ["되네르케밥"],
    description: "원곡로 도네르 케밥집",
  },
  {
    id: "bat-kebab",
    name: "바트케밥",
    category: "restaurant",
    district: "centralasia",
    lat: 37.3289386,
    lng: 126.7885723,
    address: "경기 안산시 단원구 중앙대로 441 상가동 1층 6호",
    naverPlaceId: "1077918062",
    locationSource: "naver",
    walkMinutes: 5,
    tel: "031-495-1970",
    placeUrl: "http://place.map.kakao.com/746938146",
    tags: ["케밥", "튀르키예음식"],
    description: "안산역 앞 튀르키예 케밥집",
  },

  // ── 문화체험 · 포토스팟 ───────────────────────────────────
  {
    id: "culture-center",
    name: "세계문화체험관",
    category: "experience",
    district: "centralasia",
    lat: 37.3324298,
    lng: 126.7902449,
    address: "경기 안산시 단원구 부부로 43 외국인주민지원본부 3층",
    nameAliases: ["안산시세계문화체험관"],
    naverPlaceId: "32738911",
    locationSource: "naver",
    walkMinutes: 12,
    tel: "031-481-3732",
    placeUrl: "http://place.map.kakao.com/26102511",
    tags: ["전통의상", "세계악기", "무료체험"],
    description: "세계 각국 의상·악기를 체험하는 무료 학습관",
    story:
      "외국인주민지원본부 안에 자리한 체험관으로, 하루 세 번(10:30·13:30·15:00) 세계 각국의 악기 연주, 전통의상 입어보기, 전통춤 배우기가 진행됩니다. 관광공사 등록 정보상 운영은 평일 10:00~16:00(12:00~13:00 준비시간)이고 주말·공휴일은 휴관이니, 주말 방문이라면 이곳 대신 다른 칸을 먼저 채우세요.",
    stampSlot: "culture-center",
    quiz: {
      question: "세계문화체험관의 체험 프로그램은 하루 몇 회 운영될까요?",
      options: ["1회", "3회", "상시 운영"],
      answerIndex: 1,
      hint: "이 장소의 문화 스토리에 답이 있어요.",
    },
  },
  {
    id: "borderless-photo",
    name: "국경없는거리 포토존",
    category: "photo",
    district: "chinese",
    lat: 37.329428,
    lng: 126.790589,
    address: "경기 안산시 단원구 다문화길 16 (다문화특구)",
    locationSource: "curated",
    walkMinutes: 6,
    tags: ["만국기", "세계도시 이정표", "벽화"],
    description: "세계 각국 방향·거리를 알려주는 이정표와 만국기 거리",
    story:
      "외국인주민센터 앞에는 세계 주요 도시까지의 방향과 거리를 새긴 이정표가 서 있습니다. 머리 위 만국기와 거리 곳곳의 벽화·조형물이 '국경없는 마을'이라는 원곡동의 별칭을 한 컷에 담아줍니다.",
    stampSlot: "photo-spot",
    quiz: {
      question: "원곡동의 별칭으로 알려진 이름은 무엇일까요?",
      options: ["국경없는 마을", "세계로 마을", "만국기 마을"],
      answerIndex: 0,
      hint: "이 장소의 문화 스토리에 답이 있어요.",
    },
  },
];

// 사람이 확정한 Google 장소 ID가 중복되면 서로 다른 카드에 같은 사진이 붙는다.
// 데이터 편집 시 바로 발견할 수 있도록 모듈 로드 단계에서 검증한다.
const verifiedGooglePlaceIds = SAMPLE_PLACES.flatMap((place) =>
  place.googlePlaceId ? [place.googlePlaceId] : []
);
if (new Set(verifiedGooglePlaceIds).size !== verifiedGooglePlaceIds.length) {
  throw new Error("SAMPLE_PLACES에 중복된 Google Places 장소 ID가 있습니다.");
}

const verifiedNaverPlaceIds = SAMPLE_PLACES.flatMap((place) =>
  place.naverPlaceId ? [place.naverPlaceId] : []
);
if (new Set(verifiedNaverPlaceIds).size !== verifiedNaverPlaceIds.length) {
  throw new Error("SAMPLE_PLACES에 중복된 네이버 지도 장소 ID가 있습니다.");
}

if (SAMPLE_PLACES.some((place) => !place.locationSource)) {
  throw new Error("SAMPLE_PLACES의 모든 장소에는 좌표 검증 기준이 필요합니다.");
}

export function getPlace(id: string): Place | undefined {
  return SAMPLE_PLACES.find((p) => p.id === id);
}
